---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-0
  namespace: cosmic
spec:
  selector:
    app: rabbitmq-0
  ports:
    - name: foo
      port: 1234
      targetPort: 1234
  clusterIP: None
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-1
  namespace: cosmic
spec:
  selector:
    app: rabbitmq-1
  ports:
    - name: foo
      port: 1234
      targetPort: 1234
  clusterIP: None
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: cosmic
spec:
  selector:
    rmqcluster: bubble
  ports:
    - name: "15672"
      port: 15672
      protocol: TCP
      targetPort: 15672
      nodePort: 30101
    - name: "4369"
      port: 4369
      protocol: TCP
      targetPort: 4369
      nodePort: 30102
    - name: "5671"
      port: 5671
      protocol: TCP
      targetPort: 5671
      nodePort: 30103
    - name: "5672"
      port: 5672
      protocol: TCP
      targetPort: 5672
      nodePort: 30104
    - name: "25672"
      port: 25672
      protocol: TCP
      targetPort: 25672
      nodePort: 30105
  type: NodePort
